version: '3.8'

services:
  web:
    container_name: react-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2025:80"
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
