version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: bedagya/citypay:latest
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    restart: always
